language: cpp

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++"
    - os: osx
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir build

install:
  - cmake -S . -B build
  - cmake --build build --target gtest_main
  - cmake --build build --target tests
  - cd build

script:
  - ctest
